"""Initial migration

Revision ID: eca21b20fe63
Revises: 
Create Date: 2026-03-25 15:58:27.354652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca21b20fe63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storm_probability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('alert_level', sa.String(length=16), nullable=False),
    sa.Column('kp_index_estimate', sa.Float(), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('ix_predictions_generated_at', 'predictions', ['generated_at'], unique=False)
    op.create_table('storm_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('donki_id', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=8), nullable=False, comment='GST | CME | IPS | SEP'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('impact_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kp_max', sa.Float(), nullable=True, comment='Maximum observed Kp index during storm (0-9)'),
    sa.Column('dst_min', sa.Float(), nullable=True, comment='Minimum Dst index [nT] — more negative = more intense'),
    sa.Column('cme_speed_kms', sa.Float(), nullable=True, comment='CME propagation speed [km/s] from DONKI catalog'),
    sa.Column('cme_half_angle', sa.Float(), nullable=True, comment='CME half-angle [deg] — proxy for angular width'),
    sa.Column('is_earth_directed', sa.Boolean(), nullable=False, comment='Whether the CME is flagged as Earth-directed'),
    sa.Column('is_storm', sa.Boolean(), nullable=False, comment='True if event produced Kp≥5 (G1+ storm threshold)'),
    sa.Column('severity', sa.String(length=16), nullable=True, comment='G1 | G2 | G3 | G4 | G5 (NOAA geomagnetic scale)'),
    sa.Column('source_api', sa.String(length=32), nullable=False, comment='Which API / catalog this record came from'),
    sa.Column('raw_json', sa.Text(), nullable=True, comment='Full JSON response payload from DONKI for auditability'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was written to our DB'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_storm_events_donki_id'), 'storm_events', ['donki_id'], unique=True)
    op.create_index(op.f('ix_storm_events_event_type'), 'storm_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_storm_events_is_storm'), 'storm_events', ['is_storm'], unique=False)
    op.create_index('ix_storm_events_start_time', 'storm_events', ['start_time'], unique=False)
    op.create_index('ix_storm_events_type_storm', 'storm_events', ['event_type', 'is_storm'], unique=False)
    op.create_table('telemetry',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('bx_gse', sa.Float(), nullable=False),
    sa.Column('by_gse', sa.Float(), nullable=False),
    sa.Column('bz_gse', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_telemetry_timestamp', 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('ix_storm_events_type_storm', table_name='storm_events')
    op.drop_index('ix_storm_events_start_time', table_name='storm_events')
    op.drop_index(op.f('ix_storm_events_is_storm'), table_name='storm_events')
    op.drop_index(op.f('ix_storm_events_event_type'), table_name='storm_events')
    op.drop_index(op.f('ix_storm_events_donki_id'), table_name='storm_events')
    op.drop_table('storm_events')
    op.drop_index('ix_predictions_generated_at', table_name='predictions')
    op.drop_table('predictions')
    # ### end Alembic commands ###
